---
dmx:
  # where the input comes from
  # this is the DMX Spot Controller ID
  input: 
    universe: 0
    id: 42
  

  # where the spots are.. currently limited to 1 universe
  output:
    universe: 1

# how we manage the joystick
joystick:
  controller_id: 1
  #controller_id: 0
  #wireless_id: 0
  deadzone: 5000 