---
shows:
  default:
    # this stage is in inches
    # z is height of average person ..65 inches
    stage:
      x: 300
      y: 230
      z: 65
    fixtures:
      Truss-3z:
        id: 21
        profile: ADJ_3z
        aspect: truss
        x: 157
        y: 216
        z: 71
      Truss-LS-1:
        id: 1
        profile: LED_Spot
        aspect: truss
        x: 135
        y: 216
        z: 77
      Truss-LS-2:
        id: 11
        profile: LED_Spot
        aspect: truss
        x: 177
        y: 216
        z: 77
    fixture_groups:
      test:
        - Truss-3z
#        - Truss-LS-1
        - Truss-LS-2


    fixture_aspects:
      truss: hanging
      tree: hanging,reversed

...